Column_List = ['Sequence No1', 'Current1', 'Current2', 'Current3', 'Voltage1', 'Voltage2', 'Voltage3', 'MVA1', 'MVA2', 'MVA3', 
'MW1', 'MW2', 'MW3', 'MVAR1', 'MVAR2', 'MVAR3', 'PF1', 'PF2', 'PF3', 'MVATot', 'MWTot', 'MVARTot', 'PFTot', 'ZFeedback1',
'ZFeedback2', 'ZFeedback3', 'Res1', 'Res2', 'Res3', 'Reactance1', 'Reactance2', 'Reactance3', 'ArcLength1', 'ArcLength2',
'ArcLength3', 'RWI1', 'RWI2', 'RWI3', 'NeutralCurrent', 'NeutralVolts', 'Normalized Neutral Current', 'Normalized Neutral Voltage',
'PrimaryVolts', 'VoltageLineToLine12', 'VoltageLineToLine23', 'VoltageLineToLine31', 'PhasorAngleV1I1', 'PhasorAngleV1I2', 
'PhasorAngleV1I3', 'PhasorAngleV1V2', 'PhasorAngleV1V3', 'CurrentLoadPercent1', 'CurrentLoadPercent2', 'CurrentLoadPercent3', 
'CurrentLoadPercentAvg', 'Y1', 'Y2', 'Y3', 'IOFrameReserved1', 'IOFrameReserved2', 'IOFrameReserved3', 'IOFrameReserved4',
'IOFrameReserved5', 'IOFrameReserved6', 'IOFrameReserved7', 'IOFrameReserved8', 'IOFrameReserved9', 'ArcResistance1', 'ArcResistance2',
'ArcResistance3', 'ArcEfficiency1', 'ArcEfficiency2', 'ArcEfficiency3', 'ExtinctionVoltage1', 'ExtinctionVoltage2', 'ExtinctionVoltage3',
'ReignitionVoltage1', 'ReignitionVoltage2', 'ReignitionVoltage3', 'ArcMeanPower1', 'ArcMeanPower2', 'ArcMeanPower3', 'ArcVoltage1',
'ArcVoltage2', 'ArcVoltage3', 'ActFceTap_Px3', 'ActReaTap_Px3', 'ActSubTap_Px3', 'HeatNumber3MSW', 'HeatNumber2', 'HeatNumber1',
'HeatNumber0LSW', 'BITMAP_Operation1', 'ActualCHRG_PX3', 'Reserved0_PX3', 'ChargeWt1Tons', 'ChargeWt2Tons', 'ChargeWt3Tons', 'ChargeWt4Tons',
'ChargeWt5Tons', 'ChargeWt6Tons', 'ChargeWt7Tons', 'ChargeWt8Tons', 'ChargeWt9Tons', 'ChargeWt10Tons', 'ChargeWt11Tons',
'ChargeWt12Tons', 'FurnaceTAPManSP', 'ReactorTAPManSP', 'SubstTAPManSP', 'CurrentSPKamps', 'ArcLengthManSP', 'PwrProgNumberOV', 
'SmartArcNumberOV', 'Ontime_PX3', 'OffTime_PX3', 'Res1_Operation', 'Res2_Operation', 'Res3_Operation', 'Res4_Operation', 
'Res5_Operation', 'Res6_Operation', 'Res7_Operation', 'Res8_Operation', 'Res9_Operation','Res10_Operation', 'SeqNo_PhyFrame',
'BITMAP1', 'BITMAP2', 'BITMAP3', 'BITMAP4', 'EPos1_PX3', 'EPos2_PX3', 'EPos3_PX3', 'SpoolPos1_PX3', 'SpoolPos2_PX3', 
'SpoolPos3_PX3', 'MWH_PX3', 'ChargeMWH_PX3', 'PhaseToModify_PX3', 'NewAccValue_PX3', 'ElectrodeSpeed1_PX3', 'ElectrodeSpeed2_PX3',
'ElectrodeSpeed3_PX3', 'RawElectrodePosition1', 'RawElectrodePosition2', 'RawElectrodePosition3', 'EohCounter_PX3',
'PhysicalFrameReserved2', 'PhysicalFrameReserved3', 'PhysicalFrameReserved4', 'RegOut1', 'RegOut2', 'RegOut3', 'Sp1CurrentReg',
'ManualArcLenght', 'FceTapSPtotapchanger', 'ReactorTapSPtotapchanger', 'SubstationTapSPtotapchanger', 'PwrPrgNum',
'ChargeNumber', 'PwrProgStep_PX3', 'PwrProgMWH_PX3', 'PwrProgKWHTon_PX3', 'PwrProgMode_PX3', 'PwrProgSetpoint_PX3', 'PwrProgTap_PX3',
'PwrProgReacTap_PX3', 'PwrProgSubTap_PX3', 'ElectrodeState1', 'ElectrodeState2', 'ElectrodeState3', 'Sp1Imped', 'Sp2Imped', 
'Sp3Imped', 'NCCcounter1', 'NCCcounter2', 'NCCcounter3', 'CIcounter1', 'CIcounter2', 'CIcounter3', 'SF1', 'SF2', 'SF3', 'VoltSF1', 
'VoltSF2', 'VoltSF3', 'ExtSmartFactor1', 'ExtSmartFactor2', 'ExtSmartFactor3', 'MeanSF1', 'MeanSF2', 'MeanSF3', 'MeanVoltSF1', 'MeanVoltSF2',
'MeanVoltSF3', 'MeanExtSmartFactor1', 'MeanExtSmartFactor2', 'MeanExtSmartFactor3', 'SDevSF1', 'SDevSF2', 'SDevSF3', 'SdevVoltSF1', 
'SdevVoltSF2', 'SdevVoltSF3', 'SDevExtSmartFactor1', 'SDevExtSmartFactor2', 'SDevExtSmartFactor3', 'SeqNo_mean', 'MeanCurrent1',
'MeanCurrent2', 'MeanCurrent3', 'MeanVoltage1', 'MeanVoltage2', 'MeanVoltage3', 'MeanMVA1', 'MeanMVA2', 'MeanMVA3', 'MeanMW1',
'MeanMW2', 'MeanMW3', 'MeanMVAR1', 'MeanMVAR2', 'MeanMVAR3', 'MeanPF1', 'MeanPF2', 'MeanPF3', 'MeanTotMVA', 'MeanTotMW',
'MeanTotMVAR', 'MeanTotPF', 'MeanZ1', 'MeanZ2', 'MeanZ3', 'MeanRes1', 'MeanRes2', 'MeanRes3', 'MeanReac1', 'MeanReac2', 'MeanReac3',
'MeanLng1', 'MeanLng2', 'MeanLng3', 'MnRWI1', 'MnRWI2', 'MnRWI3', 'NeutralCurrentMean', 'NeutralVoltageMean', 'PrimaryVoltageMean',
'SDevCurrent1', 'SDevCurrent2', 'SDevCurrent3', 'SDevVoltage1', 'SDevVoltage2', 'SDevVoltage3', 'SDevMVA1', 'SDevMVA2', 'SDevMVA3',
'SDevMW1', 'SDevMW2', 'SDevMW3', 'SDevMVAR1', 'SDevMVAR2', 'SDevMVAR3', 'SDevPF1', 'SDevPF2', 'SDevPF3', 'SDevTotMVA', 'SDEvTotMW',
'SDevTotMVAR', 'SDevPF', 'SDevZ1', 'SDevZ2', 'SDevZ3', 'SDevRes1', 'SDevRes2', 'SDevRes3', 'SDevReac1', 'SDevReac2', 'SDevReac3',
'SDevLength1', 'SDevLength2', 'SDevLength3', 'SDevRWI1', 'SDevRWI2', 'SDevRWI3', 'NeutralCurrentSdev', 'NeutralVoltageSdev',
'PrimaryVoltageSdev', 'I2H1', 'I2H2', 'I2H3', 'ChargeI2H1', 'ChargeI2H2', 'ChargeI2H3', 'HeatRWI1', 'HeatRWI2', 'HeatRWI3',
'ChargeRWI1', 'ChargeRWI2', 'ChargeRWI3', 'TripsWord1', 'TripsWord2', 'TripsWord3', 'TripsWord4', 'AlarmsWord1', 'PhA_NCC_SP',
'PhB_NCC_SP', 'PhC_NCC_SP', 'TransformerTap', 'HeatMWHPLC', 'ChrgMWH', 'ChargeNumb', 'ChargeWt1', 'ChargeWt2', 'ChargeWt3', 'ChargeWt4',
'ChargeWt5', 'SmartArcEnable', 'SmartArcPrg', 'HeatNumberMSW', 'HeatNumberLSW', 'PwrOnTime', 'TapTapTime', 'I2T1', 'I2T2', 'I2T3',
'PowerProgram', 'Ph1Pressure', 'Ph2Pressure', 'Ph3Pressure', 'TiltAngle', 'PanelTemp1A', 'PanelTemp2A', 'PanelTemp2B', 'PanelTemp3A',
'PanelTemp3C', 'PanelTemp4A', 'PanelTemp4C', 'PanelTemp5D1', 'PanelTemp5D2', 'PanelTemp6A', 'PanelTemp6C', 'PanelTemp7A', 'PanelTemp7E',
'PanelTemp8A', 'PanelTemp8B', 'PanelTemp9A', 'TempSumpN', 'TempSumpS', 'RoofInlet', 'RoofOutlet', 'TC1', 'TC2', 'TC3', 'TC4', 'TC5',
'CarbInject', 'FoamySlag', 'LanceFlow', 'NScavenger', 'SScavenger', 'MainDamperPos', 'SuperBagSmpPos', 'DropBoxPsi', 'DilutionAir',
'MasterProgramLog', 'CurrentRef', 'ChrgNumProtected', 'ChargeWt', 'HeatWt', 'PercWtInFce', 'ScrapPercWt', 'HeatKWHperTon', 'PowerOnTime',
'ChargeKWHperTon', 'OperKwhPerTon', 'AvgSF', 'AvgCurent', 'HeatAvgMW', 'HeatI2HperMWH', 'HeatAvgI2H', 'ChargeAvgMW', 'ChrgI2HperMWH',
'ChrgAvgI2H', 'TotMeanMw', 'PowerOff2Min', 'PowerOff5Min', 'PowerOff30Sec', 'PwrOn30sec', 'PwrOn1min', 'Furnace_Off', 'FurnaceOn', 'PowerProg',
'BalanceProg', 'BackChrgProg', 'BurnerProg', 'PostCombProg', 'CarbonInjProg', 'O2PressProg', 'ExhaustGasProg', 'WrdGrlSwTcAlarmsToPlc',
'WrdZ1SwTcAlarmsToPlc', 'WrdZ2SwTcAlarmsToPlc', 'WrdZ3SwTcAlarmsToPlc', 'WrdZ4SwTcAlarmsToPlc', 'WrdZ5SwTcAlarmsToPlc', 'CJ1NG_Mwh', 'CJ2NG_Mwh',
'CJ3NG_Mwh', 'WritePpmData', 'ValidTempSample', 'ValidPPMSample', 'ValidCarbonSample', 'ValidNewSample', 'PrehTimeCH1', 'PrehTimeCH2',
'PreheatON', 'WriteData', 'SaveLog', 'ClosePPMLog', 'EOH', 'Elec1PosFromTop', 'Elec2PosFromTop', 'Elec3PosFromTop', 'HeartBeat', 'Spare1',
'Spare2', 'Spare3', 'Spare4', 'Spare5', 'FceXfrmTapRef', 'RectorTapRef', 'SubsXfrmTapRef', 'RegModePX3', 'SpScalingPX3', 'SetPointPX3',
'MstrGainPX3', 'Curr1BalPX3', 'Curr2BalPX3', 'ReadyToChngCountDwn', 'TapReadyToChange', 'Watchdog', 'RoofWtr_KWhLss', 'DuctWtr_KWhLss',
'SideWallWtr_KWhLss', 'LimeCharged', 'DoloCharged', 'TF_Dolo', 'TF_Lime', 'Tot_LimeInj', 'TF_Carb', 'Charge_Carb', 'TotScrapWt',
'HeatCarbonSampCount', 'BurnerControlOn', 'CJ1InService', 'CJ2InService', 'CJ3InService', 'CJ1InManual', 'CJ1InAuto', 'CJ1InSmartArc',
'CJ2InManual', 'CJ2InAuto', 'CJ2InSmartArc', 'CJ3InManual', 'CJ3InAuto', 'CJ3InSmartArc', 'PercDRIWtInFce', 'PLCMoreWatchdog1',
'HMIAimTemp', 'HMIAimO2ppm', 'HMIAimCPct', 'TempEstim', 'PPMEstim', 'CarbEstim', 'HMIMessage1', 'B1_GasFlow', 'B1_O2MainFlow',
'B1_O2ShroudFlow', 'B1_CarbonFlow', 'B1_LimeFlow', 'B2_GasFlow', 'B2_O2MainFlow', 'B2_O2ShroudFlow', 'B2_CarbonFlow', 'B2_LimeFlow',
'B3_GasFlow', 'B3_O2MainFlow', 'B3_O2ShroudFlow', 'B3_CarbonFlow', 'B3_LimeFlow', 'B1_GasRef', 'B1_O2MainRef', 'B1_O2ShroudRef', 'B1_CarbonRef',
'B1_LimeRef', 'B2_GasRef', 'B2_O2MainRef', 'B2_O2ShroudRef', 'B2_CarbonRef', 'B2_LimeRef', 'B3_GasRef', 'B3_O2MainRef', 'B3_O2ShroudRef',
'B3_CarbonRef', 'B3_LimeRef', 'B1_GasCns', 'B1_O2MainCns', 'B1_O2ShroudCns', 'B1_CarbonCns', 'B1_LimeCns', 'B2_GasCns', 'B2_O2MainCns',
'B2_O2ShroudCns', 'B2_CarbonCns', 'B2_LimeCns', 'B3_GasCns', 'B3_O2MainCns', 'B3_O2ShroudCns', 'B3_CarbonCns', 'B3_LimeCns', 'TotalGasCns',
'TotalO2Cns', 'TotalCarbonCns', 'BurnersReserved1', 'BurnersReserved2', 'BurnersReserved3', 'BurnersReserved4', 'BurnersReserved5', 'BurnersReserved6',
'AdditionsLimeCharge', 'AdditionsDoloCharge', 'AdditionsCarbCharg', 'AdditionsTFDolo', 'AdditionsTFLime', 'AdditionsTFCarbon', 'AdditionsLimeInj',
'AdditionsDoloInj', 'AdditionsCarbInj', 'AdditionsReserve1', 'AdditionsReserve2', 'AdditionsReserve3', 'Scrap1Wt', 'Scrap2Wt', 'Scrap3Wt', 'Scrap4Wt',
'Scrap5Wt', 'Scrap6Wt', 'Scrap7Wt', 'Scrap8Wt', 'Scrap9Wt', 'Scrap10Wt', 'ChargeCarbWt', 'ChargeSiWt', 'CarbFromScrap', 'SiFromScrap', 'MnFromScrap',
'DensityForScrap', 'PercInFceHeatWt', 'PercInFceDRI', 'PercInFceHotDRI', 'PercInFceHotMetal', 'PercInFceHBI', 'DRIWt', 'ScrapCarbon_O2Req', 'ScrapSi_O2Req',
'ScrapMn_O2Req', 'ChrgCarb_O2Req', 'TFCarb_O2Req', 'InjCarb_O2Req', 'CH4_O2Req', 'TotO2Req', 'TotO2Used/ton', 'TotO2Req/ton', 'FreeO2PerTon', 'TempSample',
'PPMSample', 'CarbSample', 'PPMestim', 'AimPPM', 'ChemicalEnergyPerSteelTon', 'ChemicalEnergyMnOxi', 'ChemicalEnergySiOxy', 'ChemicalEnergyFeOxy',
'ChemicalEnergyCcharge', 'ChemicalEnergyTFCarb', 'ChemicalEnergyCinj', 'ChemicalEnergyGasOxi', 'EnergyinMetal', 'WaterLosses', 'RoofLosses', 'DuctLosses',
'OffGasLosses', 'GasPreheat', 'GasMelting', 'O2RatioPreheat', 'O2RatioMelting', 'GasEnergyPreheat', 'GasEnergyMelting', 'TotalPreheatTime', 'MeltingTime',
'EnergyEfficiency', 'UnaccountableIn', 'UnaccountableOut', 'ChemicalEnergyAlOxy', 'ChemicalEnergyElectCarb', 'SaMinO2Required(CO)', 'SaMaxO2Required(CO2)',
'FreeO2Oper', 'FreeO2Offset', 'FreeO2ConvToPpm', 'FreeO2ConvToPpmAdjusted', 'PpmEstimAtSample', 'PpmEstimDiff', 'TempEstimToHMI', 'TempEstimToHMILastScan',
'EnergyReqdForScrap', 'OffGasEnergyLosseskWh', 'MWLosses', 'TempEstimBalance', 'EnergyInn', 'EnergyOut', 'TotalCarbInjRef', 'TotalO2Flow', 'TotCarbonInjFlow',
'CotoCO2Ratio', 'SlagAnalysis_AcidsLb', 'SlagAnalysis_B3Actual', 'SlagAnalysis_SlagMassActual', 'SlagAnalysis_SlagEnergyActual', 'SlagAnalysis_B3Target',
'SlagAnalysis_FeOMnOTarget', 'SlagAnalysis_MgOSupSatTarget', 'SlagAnalysis_Al2O3analysis', 'SlagAnalysis_CaOanalysis', 'SlagAnalysis_Cr2O3analysis', 
'SlagAnalysis_MgOanalysis', 'SlagAnalysis_MnOanalysis', 'SlagAnalysis_P2O5analysis', 'SlagAnalysis_Sanalysis', 'SlagAnalysis_SiO2analysis', 'SlagAnalysis_TiO2analysis',
'SlagAnalysis_V2O5analysis', 'SlagAnalysis_FeOanalysis', 'SlagAnalysis_TempEstimSlag', 'SlagAnalysis_FeOMnOEstim', 'SlagAnalysis_FeODual', 'SlagAnalysis_MgODual',
'SlagAnalysis_MgOSatX', 'SlagAnalysis_MgOSaturation', 'SlagAnalysis_TargetX', 'SlagAnalysis_TargetY', 'SlagAnalysis_MgOSatAnalysis', 'SlagAnalysis_MgOSatDiffAnalysis',
'SlagAnalysis_LimeRecommended', 'SlagAnalysis_DoloRecommended', 'SlagAnalysis_SlagMassRecomm', 'SlagAnalysis_SlagEnergyRecomm', 'LimeRecomCh1', 'DoloRecomCh1',
'SlagMassCh1', 'SlagEnergyCh1', 'LimeRecomCh2', 'DoloRecomCh2', 'SlagMassCh2', 'SlagEnergyCh2', 'LimeRecomCh3', 'DoloRecomCh3', 'SlagMassCh3', 'SlagEnergyCh3',
'SlagSample_Al2O3', 'SlagSample_CaO', 'SlagSample_Cr2O3', 'SlagSample_MgO', 'SlagSample_MnO', 'SlagSample_P2O5', 'SlagSample_S', 'SlagSample_SiO2', 'SlagSample_TiO2', 
'SlagSample_V2O5', 'SlagSample_FeO', 'SlagSample_TempSampSlagAnalysis', 'SlagSample_B3Sample', 'SlagSample_DoloSample', 'SlagSample_LimeSample',
'SlagSample_MgOSaturationSample', 'SlagSample_MgOSatDiff', 'SlagSample_FeODualSample', 'SlagSample_MgODualSample', 'SlagSample_SaturationX',
'SlagSample_SaturationY', 'SlagSample_SampleX', 'SlagSample_SampleY', 'SlagSample_kWhPerTonSlagSamp', 'SlagSample_POnSlagSampl', 'SlagSample_ArcEffSlagSamp',
'SlagSample_PPMSlagSamp', 'SlagSample_CarbSlagSamp', 'SP_B1_NG', 'SP_B2_NG', 'SP_B3_NG', 'SP_B1_MainO2', 'SP_B2_MainO2', 'SP_B3_MainO2', 'SP_Inj1_C',
'SP_Inj2_C', 'SP_Inj3_Lime', 'HMIMessage2', 'Step', 'M1FreeO2ConvToPpm', 'M2TotO2HotHeel', 'M2FreeO2Oper', 'M2FreeO2ConvToPpmAdjusted', 'M2FreeO2OffsetClamp',
'M2PpmEstimAtSample', 'M2PPMSample_FeO', 'M2TempSample_FeO', 'M2FreeO2Sample_FeO', 'M3TotO2HotHeel', 'M3FreeO2Oper', 'M3FreeO2ConvToPpmAdjusted',
'M3FreeO2OffsetClamp', 'M3PpmEstimAtSample', 'M3PpmSample', 'M3TempAtSample', 'M3FreeO2AtSample', 'EnergyOffset', 'TotEstimatedLosses', 'TotalMeasuredLosses',
'EnergyLossesKWH', 'LossesByPowerOff', 'LossesByPowerOn', 'MasterEnable', 'Hi-Jet1Enable', 'Hi-Jet2Enable', 'Lime-JetEnable', 'CarbInj1Enable', 'CarbInj2Enable',
'LimeInjEnable', 'FreeO2Diff100', 'PLCFluxB1Carbon', 'PLCFluxB2Carbon', 'PLCFluxB3Carbon', 'OxydationAdjust', 'PowerDemand', 'SFNotFollowing', 'PwrLvlFbk', 'O2scfCarbInjLb', 'HeatNumber']